### ISSUE TITLE
Compatibilty Redmine 4.0

### ISSUE THREAD

**Issue by RomuAdq** [chrodriguez/redmine_omniauth_saml#43]
Hello, the (useful) plugin is not compatible with Redmine 4.0 branch.
Here is the error when using : `rake redmine:plugins:migrate RAILS_ENV=production`

```
NoMethodError: undefined method `alias_method_chain' for User (call 'User.connection' to establish a connection):Class
/var/www/html/plugins/redmine_omniauth_saml/lib/redmine_omniauth_saml/user_patch.rb:29:in `<class:User>'
/var/www/html/plugins/redmine_omniauth_saml/lib/redmine_omniauth_saml/user_patch.rb:3:in `<top (required)>'
/var/www/html/plugins/redmine_omniauth_saml/init.rb:4:in `<top (required)>'
/var/www/html/lib/redmine/plugin.rb:175:in `block in load'
/var/www/html/lib/redmine/plugin.rb:166:in `each'
/var/www/html/lib/redmine/plugin.rb:166:in `load'
/var/www/html/config/initializers/30-redmine.rb:21:in `<top (required)>'
/var/www/html/config/environment.rb:14:in `<top (required)>'
Tasks: TOP => redmine:plugins:migrate => environment
```

Any chance to make it compatible ?

Thank you !

**Comment by nayuta** [comment]
Hi, I'd faced the same problem and try to fix it. Could you test the unchecked item?

https://github.com/chrodriguez/redmine_omniauth_saml/pull/44

**Comment by nayuta** [comment]
Hi, I've fix it at #44 . I'm waiting to check by @chrodriguez .

~While it, I've open my repository. I'll remove this repository when it merged.~

~https://github.com/nayuta/redmine_omniauth_saml/~

It merged! Thank you @chrodriguez !
