### ISSUE TITLE
Can't mass-assign protected attributes for User: login

### ISSUE THREAD

**Issue by danielamkaer** [chrodriguez/redmine_omniauth_saml#5]
Seems to be an issue.

Log:
```
Started POST "/auth/saml/callback" for 185.17.216.112 at 2015-08-14 13:51:07 +0000
Processing by AccountController#login_with_saml_callback as HTML
  Parameters: {"SAMLResponse"=>"*SNIP*", "provider"=>"saml"}
  Current user: anonymous
WARNING: Can't mass-assign protected attributes for User: login
	lib/redmine/sudo_mode.rb:63:in `sudo_mode'
Completed 422 Unprocessable Entity in 15ms (ActiveRecord: 5.4ms)

ActiveRecord::RecordInvalid (Validation failed: Email skal udfyldes, Login skal udfyldes, Fornavn skal udfyldes, Efternavn skal udfyldes):
  lib/redmine/sudo_mode.rb:63:in `sudo_mode'
```

**Comment by chrodriguez** [comment]
@danielamkaer  sorry for the late answer. Have you solved this issue? I've never got this error. Can you explain the steps to reproduce it?
